cuda_device : '0'


numpy_x_path : './data/numpy_data/x/'
numpy_y_path : './data/numpy_data/y/'
numpy_test_path : './data/numpy_data/test/'

data_x_path : './data/train_x/'
data_y_path : './data/train_y/'
data_test_path  : './data/test/'

train_test_ratio  : [7,3]
batch_size  : 8
epochs  : 700
LR  : 0.001

save_every : 1

steps_per_epoch : 100


patch_list  : [[256,256],[256,256],[256,256],[256,256],[256,256],[256,256]]
target_image_size : [512,512]


# predict_vdsr variables

json_path :  'model/vdsr_architecture.json'
test_images_path  : 'data/test'
test_dest_path  : '../../results'
pred_tgt_size : [512,512]


max_pixel_val : 3000

np_slices_path : './results/'
np_stitched_output_path  : './numpy_stitch_output/'


# dicom slices path

dicom_x_path  : './data/dicom_to_numpy/x/'
dicom_y_path  : './data/dicom_to_numpy/y/'
dicom_test_path : './data/dicom_to_numpy/test/'

dicom_output  : './numpy_to_dicom/'

dicom_patch_file : './dicom_sample_patch/sample.dcm'